version: '3.5'

networks:
  solace_msg_net:
    name: solace_msg_net
    external: false
    driver: bridge

services:

  # Tempo
  tempo:
    image: grafana/tempo:1.5.0
    restart: always
    command: [ "-search.enabled=true", "-config.file=/etc/tempo.yaml" ]
    networks:
      - solace_msg_net
    container_name: tempo1
    hostname: tempo
    volumes:
      - ./tempo-config.yaml:/etc/tempo.yaml
      - ./tempo-overrides.yaml:/etc/overrides.yaml
      - ./tempo-data:/tmp/tempo
    ports:
      - "3200:3200"
      - "4317:4317"
    healthcheck:
      interval: 5s
      retries: 10
      test: wget --no-verbose --tries=1 --spider http://localhost:3200/status || exit 1


  # Collector
  otel-collector:
    image: ${OTELCOL_IMG}
    command: ["--config=/etc/otel-collector-config.yaml", "${OTELCOL_ARGS}"]
    hostname: otelcollector
    networks:
      - solace_msg_net
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "1888:1888"   # pprof extension
      - "8888:8888"   # Prometheus metrics exposed by the collector
      - "8889:8889"   # Prometheus exporter metrics
      - "13133:13133" # health_check extension
      - "55679:55679" # zpages extension

  solbroker:
    image: $PUBSUB_IMAGE
    hostname: $PUBSUB_HOSTNAME
    networks:
      - solace_msg_net
    env_file:
      - ./solace_config_keys.env
    ports:
      - "2222:2222"
      - "8080:8080"
      - "55443:55443"
      - "55445:55445"
      - "${PUBSUB_PORT_NUMBER}:55555"
      - "55556:55556"
      - "5671:5671"
      - "5672:5672"
      - "5550:5550"
      - "1943:1943"
      - "8008:8008"
    shm_size: 2g
    ulimits:
      memlock: -1
      nofile:
        soft: 2448
        hard: 42192

  grafana:
    image: grafana/grafana:9.2.2
    container_name: grafana1
    hostname: grafana
    networks:
      - solace_msg_net
    depends_on:
      tempo:
        condition: service_healthy
#      prometheus:
#        condition: service_healthy
    volumes:
      - ./grafana-bootstrap.ini:/etc/grafana/grafana.ini
      - ./grafana-datasources.yaml:/etc/grafana/provisioning/datasources/datasources.yaml
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    healthcheck:
      interval: 5s
      retries: 10
      test: wget --no-verbose --tries=1 --spider http://localhost:3000 || exit 1
